### ISSUE TITLE
renderer.handleinputs()

### ISSUE THREAD

**Issue by 0x78f1935** [nx-python/imgui-switch#1]
Hey all, So I'm working on a keyboard. The layout is fine so imagine a complete virtual keyboard.
Controller input are all fine. So when you select a key and you press the A button the button will trigger and does it's job.

Even tho when I want to use touch, a little mouse appears and even the button get selected. But the action behind the button won't trigger. 

    def keyboard_key(self, key, same_line=False):
        if same_line:
            imgui.same_line()

        imgui.push_style_color(imgui.COLOR_BUTTON, *self.FOLDER_COLOR)
        if imgui.button(str(key), width=60, height=60):
            pass # Placeholder for example. Action should be here
        imgui.pop_style_color(1)

The above function is how I create a key. It's what I call in the mainloop to create the button in the layout.

    def main(self):
        while True:
            self.renderer.handleinputs()

This is the start of the mainloop. self.renderer links to:

    from imgui.integrations.nx import NXRenderer
    def __init__(self):
        # (r, g, b)
        self.FOLDER_COLOR = self.colorToFloat((230, 126, 34))
        self.PYFILE_COLOR = self.colorToFloat((46, 204, 113))
        self.FILE_COLOR = self.colorToFloat((41, 128, 185))

        self.renderer = NXRenderer()
        self.currentDir = os.getcwd()

It's all written in class format. Perhaps there is something I miss,

**Comment by elnardu** [comment]
TextInput was stealing focus from buttons. 
It also looks like it somewhat related to this issue https://github.com/ocornut/imgui/issues/1418
